"""
Django settings for avatar_interview_platform project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

# Load environment variables from .env file
load_dotenv()

# -----------------------------
# BASE DIR
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# -----------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------
# SECURITY SETTINGS
# SECURITY WARNING: keep the secret key used in production secret!
# -----------------------------
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is not set!")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

#open Ai
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', default='')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', default='')
GROQ_API_KEY = os.getenv('GROQ_API_KEY', default='')


ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,.up.railway.app').split(',')
CSRF_TRUSTED_ORIGINS = os.getenv(
    'CSRF_TRUSTED_ORIGINS',
    'https://localhost,https://127.0.0.1'
).split(',')

BASE_URL = os.getenv('BASE_URL', 'http://localhost:8000')

# -----------------------------
# FRONTEND URL
# -----------------------------
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://orbit-one-psi.vercel.app')
# Extra hostnames allowed for WebSocket Origin (comma-separated); FRONTEND_URL host is always allowed
WEBSOCKET_EXTRA_ALLOWED_ORIGIN_HOSTS = [
    h.strip() for h in os.getenv('WEBSOCKET_EXTRA_ALLOWED_ORIGIN_HOSTS', '').split(',') if h.strip()
]

# -----------------------------
# INSTALLED APPS
# -----------------------------
INSTALLED_APPS = [

    'daphne',

    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom apps
    'accounts',
    'companies',
    
    
    'channels',


    'meetings',
    'avatars',
    'invitations',
    'notifications',
    'system_admin',
    'shared',

    # Centeral Storage 
    'storages',

    # REST API
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    # 'django_ratelimit' this need to implemented latter
    
    # CORS
    'corsheaders',
]


# ASGI Application
ASGI_APPLICATION = 'avatar_interview_platform.asgi.application'



# Channels Configuration
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [REDIS_URL],
        },
    },
}

# WebRTC Configuration
WEBRTC_CONFIG = {
    'ice_servers': [
        {'urls': 'stun:stun.l.google.com:19302'},
        {'urls': 'stun:stun1.l.google.com:19302'},
        {'urls': 'stun:stun2.l.google.com:19302'},
        # Add TURN server later if needed
        # {
        #     'urls': 'turn:your-turn-server.com:3478',
        #     'username': 'your_username',
        #     'credential': 'your_password'
        # }
    ]
}

# -----------------------------
# FILE STORAGE CONFIG
# -----------------------------
USE_R2 = os.getenv('USE_R2', '').lower() == 'true'
# Central storage configuration using STORAGES (Django 5+)
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage" if USE_R2 else "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

if USE_R2:
    AWS_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('R2_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.getenv('R2_ENDPOINT_URL')
    AWS_S3_REGION_NAME = 'auto'
    AWS_S3_CUSTOM_DOMAIN = os.getenv('R2_PUBLIC_URL').replace('https://', '')

    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'


# -----------------------------
# AUTHENTICATION
# -----------------------------
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be first
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
# ]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "ngrok-skip-browser-warning",  # Add this header
]

# -----------------------------
# URL & TEMPLATES
# -----------------------------
ROOT_URLCONF = 'avatar_interview_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'avatar_interview_platform.wsgi.application'


# -----------------------------
# DATABASE
# -----------------------------
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'avatar'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# -----------------------------
# PASSWORD VALIDATION
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
# -----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# -----------------------------
# INTERNATIONALIZATION
# https://docs.djangoproject.com/en/5.0/topics/i18n/
# -----------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -----------------------------
# STATIC FILES (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
# -----------------------------
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# -----------------------------
# EMAIL / SMTP SETTINGS
# -----------------------------
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)





# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'


# Celery Beat Schedule
from celery import Celery
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'fetch-inbox-emails': {
        'task': 'notifications.tasks.fetch_inbox_emails',
        'schedule': crontab(minute='*/15'),  # Every 15 minutes
    },
    'generate-daily-analytics': {
        'task': 'notifications.tasks.generate_daily_analytics',
        'schedule': crontab(hour=1, minute=0),  # Daily at 1 AM
    },
    'retry-failed-emails': {
        'task': 'notifications.tasks.retry_failed_emails',
        'schedule': crontab(minute='*/30'),  # Every 30 minutes
    },
    'cleanup-old-emails': {
        'task': 'notifications.tasks.cleanup_old_emails',
        'schedule': crontab(day_of_week=0, hour=2),  # Weekly on Sunday at 2 AM
    },
    'send-scheduled-campaigns': {
        'task': 'notifications.tasks.send_scheduled_campaigns',
        'schedule': crontab(minute='*/5'),  # Every 5 minutes
    },
    'analyze-inbox-with-ai': {
        'task': 'notifications.tasks.analyze_inbox_with_ai',
        'schedule': crontab(minute='*/20'),  # Every 20 minutes
    },
    'mark-expired-meetings-not-held': {
        'task': 'meetings.tasks.mark_expired_meetings_not_held',
        'schedule': crontab(minute='*/10'),  # Every 10 minutes
    },
    'close-expired-in-progress-meetings': {
        'task': 'meetings.tasks.close_expired_in_progress_meetings',
        'schedule': crontab(minute='*/5'),  # Every 5 minutes
    },
    'send-meeting-end-warnings': {
        'task': 'meetings.tasks.send_meeting_end_warnings',
        'schedule': crontab(minute='*'),  # Every minute to catch 5-minute warnings accurately
    },
}



# Logging Configuration - console only (suitable for Railway)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'meetings':              {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'notifications':         {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'avatars':               {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'companies':             {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'accounts':              {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'shared':                {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'system_admin':          {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'avatar_interview_platform': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'django':                {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'django.request':        {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'django.server':         {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'django.db.backends':    {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
        'celery':                {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'celery.worker':         {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Email attachment limits
MAX_ATTACHMENT_SIZE = 5 * 1024 * 1024  # 5MB
ALLOWED_ATTACHMENT_TYPES = [
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'image/jpeg',
    'image/png',
    'image/gif',
]

# ==================== Encryption Configuration ====================
# SMTP_ENCRYPTION_KEY key for SMTP password encryption
SMTP_ENCRYPTION_KEY = os.getenv("SMTP_ENCRYPTION_KEY")

# -----------------------------
# UPLOAD LIMITS
# -----------------------------
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB


# -----------------------------
# REST FRAMEWORK CONFIG
# -----------------------------
REST_FRAMEWORK = {
    # Authentication using JWT
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],

    # Pagination settings
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # You can change this as needed

    # Filtering, searching, ordering
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    # JSON-only responses (no Browsable API in production)
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],

    # Allow JSON, form data, and file uploads
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}


# -----------------------------
# JWT SETTINGS
# -----------------------------
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,  # Issues new refresh token on refresh
    'BLACKLIST_AFTER_ROTATION': True,  # Invalidates old refresh tokens
}

# -----------------------------
# DEFAULT PRIMARY KEY FIELD TYPE
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
# -----------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# minutes=60
# Cache settings (using Redis in production)
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         },
#         'KEY_PREFIX': 'avatar',
#         'TIMEOUT': 900,  # 15 minutes
#     }
# }

# # Security settings for production
# if not DEBUG:
#     SECURE_SSL_REDIRECT = True
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True
#     SECURE_BROWSER_XSS_FILTER = True
#     SECURE_CONTENT_TYPE_NOSNIFF = True
#     X_FRAME_OPTIONS = 'DENY'





# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/