# Generated by Django 5.2.7 on 2026-01-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone_number',
        ),
    ]
