# Generated by Django 5.2.7 on 2026-02-09 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_email', models.BooleanField(default=True)),
                ('notifications_meetings', models.BooleanField(default=True)),
                ('notifications_campaigns', models.BooleanField(default=True)),
                ('security_session_timeout', models.IntegerField(default=30, help_text='Session timeout in minutes')),
                ('security_password_expiry', models.IntegerField(default=90, help_text='Password expiry in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
