# Generated by Django 5.2.7 on 2026-02-02 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_rejection_remarks_company_status'),
        ('meetings', '0003_add_meeting_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0, help_text='Overall rating (1-5)')),
                ('behavioral_score', models.PositiveSmallIntegerField(default=0, help_text='Behavioral score (1-5)')),
                ('technical_score', models.PositiveSmallIntegerField(default=0, help_text='Technical score (1-5)')),
                ('feedback_text', models.TextField(blank=True, help_text='Detailed feedback/remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to='companies.companyperson')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='meetings.meeting')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'interviewer'), name='unique_interviewer_meeting_feedback')],
            },
        ),
    ]
