# Generated by Django 5.2.7 on 2026-02-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meetingfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='enable_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_file',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
