# Generated by Django 5.2.7 on 2026-02-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meeting_enable_recording_meeting_recording_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='recording_by',
            field=models.CharField(blank=True, help_text='ID of the participant currently recording', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='recording_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('recording', 'Recording'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
