# Generated by Django 5.2.7 on 2025-12-11 20:44

import avatars.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the avatar', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of name', max_length=255, unique=True)),
                ('vrm_file', models.FileField(help_text='VRM avatar file', upload_to=avatars.models.avatar_vrm_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['vrm'])])),
                ('preview_image', models.ImageField(help_text='Preview image of the avatar', upload_to=avatars.models.avatar_image_path)),
                ('description', models.TextField(blank=True, help_text='Optional description of the avatar', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this avatar is available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='avatars_ava_slug_3b13da_idx'), models.Index(fields=['is_active'], name='avatars_ava_is_acti_598311_idx')],
            },
        ),
    ]
