# Generated by Django 5.2.7 on 2026-01-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0003_backfill_cached_file_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='preview_image_url',
            field=models.URLField(blank=True, help_text='Cached URL for preview image (computed at upload time)', null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='vrm_file_size_bytes',
            field=models.BigIntegerField(default=0, help_text='Cached file size in bytes (computed at upload time)'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='vrm_file_url',
            field=models.URLField(blank=True, help_text='Cached URL for VRM file (computed at upload time)', null=True),
        ),
    ]
