# Generated by Django 5.2.7 on 2026-03-14 16:23

import avatars.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0004_alter_avatar_preview_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Preview image of the avatar', null=True, upload_to=avatars.models.avatar_image_path),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='vrm_file',
            field=models.FileField(blank=True, help_text='VRM avatar file', null=True, upload_to=avatars.models.avatar_vrm_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['vrm'])]),
        ),
    ]
