# Generated by Django 5.2.7 on 2025-12-11 20:44

import companies.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avatars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_type', models.CharField(blank=True, choices=[('startup', 'Startup'), ('sme', 'SME'), ('enterprise', 'Enterprise'), ('non_profit', 'Non-Profit'), ('government', 'Government'), ('educational', 'Educational'), ('freelancer', 'Freelancer'), ('ngo', 'NGO'), ('cooperative', 'Cooperative')], default='startup', max_length=20)),
                ('industry', models.CharField(blank=True, choices=[('tech', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail / E-Commerce'), ('media', 'Media & Entertainment'), ('agriculture', 'Agriculture'), ('real_estate', 'Real Estate'), ('transport', 'Transportation & Logistics'), ('energy', 'Energy & Utilities'), ('consulting', 'Consulting & Professional Services'), ('hospitality', 'Hospitality & Tourism'), ('construction', 'Construction & Infrastructure'), ('telecom', 'Telecommunications'), ('other', 'Other')], default='tech', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=companies.models.company_logo_upload_path)),
                ('description', models.TextField(blank=True)),
                ('address_country', models.CharField(blank=True, max_length=50, null=True)),
                ('address_city', models.CharField(blank=True, max_length=50, null=True)),
                ('address_street', models.CharField(blank=True, max_length=100, null=True)),
                ('address_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('support_email', models.EmailField(default='support@example.com', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('ceo', 'CEO'), ('cfo', 'CFO'), ('coo', 'COO'), ('cto', 'CTO'), ('cio', 'CIO'), ('cmo', 'CMO'), ('cmc', 'Chief Marketing Officer'), ('manager', 'Manager'), ('team_lead', 'Team Lead'), ('developer', 'Developer / Engineer'), ('designer', 'Designer'), ('qa', 'QA / Tester'), ('product_owner', 'Product Owner'), ('project_manager', 'Project Manager'), ('hr', 'HR'), ('recruiter', 'Recruiter'), ('intern', 'Intern'), ('interviewer', 'Interviewer'), ('consultant', 'Consultant'), ('advisor', 'Advisor'), ('board_member', 'Board Member'), ('other', 'Other')], default='interviewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_people', to='avatars.avatar')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook/Office365'), ('yahoo', 'Yahoo Mail'), ('zoho', 'Zoho Mail'), ('custom', 'Custom Domain')], default='gmail', max_length=20)),
                ('smtp_host', models.CharField(help_text='e.g., smtp.gmail.com', max_length=255)),
                ('smtp_port', models.IntegerField(help_text='587 for TLS, 465 for SSL')),
                ('smtp_username', models.EmailField(help_text='Your email address', max_length=254)),
                ('smtp_password', models.TextField(help_text='Encrypted password')),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS (recommended for port 587)')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL (for port 465)')),
                ('from_email', models.EmailField(help_text='Display email address', max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='Display name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('test_error', models.TextField(blank=True, help_text='Last test error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smtp_config', to='companies.company')),
            ],
            options={
                'verbose_name': 'SMTP Configuration',
                'verbose_name_plural': 'SMTP Configurations',
            },
        ),
    ]
