# Generated by Django 5.2.7 on 2025-12-11 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text="User's prompt for AI")),
                ('context', models.JSONField(blank=True, default=dict, help_text='Additional context')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tone', models.CharField(max_length=50)),
                ('model_used', models.CharField(default='gpt-4', max_length=50)),
                ('tokens_used', models.IntegerField(default=0)),
                ('generation_time', models.FloatField(help_text='Time in seconds')),
                ('was_used', models.BooleanField(default=False)),
                ('user_rating', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_drafts', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('recipient_type', models.CharField(choices=[('all', 'All Company People'), ('role', 'Specific Role'), ('custom', 'Custom Selection')], default='custom', max_length=20)),
                ('recipient_role', models.CharField(blank=True, max_length=20, null=True)),
                ('html_content', models.TextField()),
                ('plain_content', models.TextField(blank=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text='AI analysis results')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('opened_count', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, related_name='email_campaigns', to='companies.companyperson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=100)),
                ('to_email', models.EmailField(max_length=254)),
                ('to_name', models.CharField(blank=True, max_length=100)),
                ('cc_emails', models.JSONField(blank=True, default=list)),
                ('bcc_emails', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField()),
                ('plain_content', models.TextField(blank=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text='Sentiment, tone, readability scores')),
                ('ai_suggestions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='draft', max_length=20)),
                ('tracking_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='notifications.emailcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('invitation', 'Interview Invitation'), ('reminder', 'Interview Reminder'), ('feedback', 'Interview Feedback'), ('rejection', 'Rejection Letter'), ('offer', 'Job Offer'), ('welcome', 'Welcome Email'), ('notification', 'General Notification'), ('custom', 'Custom Template')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField(help_text='HTML email content with {{variables}}')),
                ('ai_tone', models.CharField(blank=True, help_text='e.g., professional, friendly, formal', max_length=50)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary of template')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.emailtemplate'),
        ),
        migrations.CreateModel(
            name='InboxEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=100)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('html_content', models.TextField(blank=True)),
                ('plain_content', models.TextField(blank=True)),
                ('received_at', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary')),
                ('ai_category', models.CharField(blank=True, max_length=50)),
                ('ai_sentiment', models.CharField(blank=True, max_length=20)),
                ('ai_priority', models.IntegerField(default=0, help_text='0-10 priority score')),
                ('thread_id', models.CharField(blank=True, max_length=255)),
                ('in_reply_to', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_emails', to='companies.company')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='email_attachments/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField(help_text='Size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notifications.email')),
                ('inbox_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notifications.inboxemail')),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='EmailAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('emails_sent', models.IntegerField(default=0)),
                ('emails_failed', models.IntegerField(default=0)),
                ('emails_opened', models.IntegerField(default=0)),
                ('emails_clicked', models.IntegerField(default=0)),
                ('emails_bounced', models.IntegerField(default=0)),
                ('emails_received', models.IntegerField(default=0)),
                ('open_rate', models.FloatField(default=0.0)),
                ('click_rate', models.FloatField(default=0.0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_analytics', to='companies.company')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('company', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['company', 'status'], name='notificatio_company_b13657_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['to_email', '-created_at'], name='notificatio_to_emai_1628bf_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['tracking_id'], name='notificatio_trackin_bda33c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='inboxemail',
            index=models.Index(fields=['company', '-received_at'], name='notificatio_company_61f872_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxemail',
            index=models.Index(fields=['message_id'], name='notificatio_message_2eae23_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxemail',
            index=models.Index(fields=['thread_id'], name='notificatio_thread__c25767_idx'),
        ),
    ]
