# Generated by Django 5.2.7 on 2026-02-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_rejection_remarks_company_status'),
        ('notifications', '0002_add_user_timezone_to_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('meeting_starting', 'Meeting Starting Soon'), ('meeting_started', 'Meeting Started'), ('meeting_ended', 'Meeting Ended'), ('meeting_cancelled', 'Meeting Cancelled'), ('meeting_rescheduled', 'Meeting Rescheduled'), ('meeting_invitation', 'New Meeting Invitation'), ('avatar_added', 'New Avatar Added'), ('avatar_updated', 'Avatar Updated'), ('email_sent', 'Email Campaign Sent'), ('email_completed', 'Email Campaign Completed'), ('feedback_received', 'New Feedback Received'), ('feedback_submitted', 'Feedback Submitted'), ('company_approved', 'Company Approved'), ('company_rejected', 'Company Rejected'), ('interviewer_added', 'New Interviewer Added'), ('system', 'System Notification')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='notificatio_company_3d4ddf_idx'), models.Index(fields=['company', 'is_read'], name='notificatio_company_df0aba_idx')],
            },
        ),
    ]
