# Generated by Django 5.2.7 on 2026-02-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('meeting_starting', 'Meeting Starting Soon'), ('meeting_started', 'Meeting Started'), ('meeting_ended', 'Meeting Ended'), ('meeting_cancelled', 'Meeting Cancelled'), ('meeting_rescheduled', 'Meeting Rescheduled'), ('meeting_invitation', 'New Meeting Invitation'), ('avatar_added', 'New Avatar Added'), ('avatar_updated', 'Avatar Updated'), ('email_sent', 'Email Campaign Sent'), ('email_completed', 'Email Campaign Completed'), ('feedback_received', 'New Feedback Received'), ('feedback_submitted', 'Feedback Submitted'), ('company_approved', 'Company Approved'), ('company_rejected', 'Company Rejected'), ('interviewer_added', 'New Interviewer Added'), ('recording_ready', 'Meeting Recording Ready'), ('system', 'System Notification')], max_length=50),
        ),
    ]
